# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-16 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestanp',
            new_name='timestamp',
        ),
    ]
